### ISSUE TITLE
Empty array & chunk definition

### ISSUE THREAD

**Issue by thomascoquet** [zarr-developers/zarr#303]
```
import zarr

store = zarr.DirectoryStore('data')
r = zarr.open_group(store=store)

z1 = r.full('V1', None,
            shape=(0,),
            chunks=None,
            dtype='i4',
            compressor=None)

print(z1[:])

z2 = r.full('V2', None,
            shape=(1,),
            chunks=(None,),
            dtype='i4',
            compressor=None)

print(z2[:])

z3 = r.full('V3', None,
            shape=(0,),
            chunks=(None,),
            dtype='i4',
            compressor=None)

print(z3[:])
```

#### Problem description

An exception is raised when array has a length of 0 & chunk is specified using ` (None,)` .
Result of above code:
```

[]
[897988541]
Traceback (most recent call last):
  File "/home/tom/PycharmProjects/starling-hcs/forest-penrose-zcube/examples/example_raster.py", line 31, in <module>
    print(z3[:])
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/core.py", line 559, in __getitem__
    return self.get_basic_selection(selection, fields=fields)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/core.py", line 685, in get_basic_selection
    fields=fields)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/core.py", line 725, in _get_basic_selection_nd
    indexer = BasicIndexer(selection, self)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/indexing.py", line 279, in __init__
    dim_indexer = SliceDimIndexer(dim_sel, dim_len, dim_chunk_len)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/indexing.py", line 113, in __init__
    self.nchunks = ceildiv(self.dim_len, self.dim_chunk_len)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/indexing.py", line 97, in ceildiv
    return int(np.ceil(a / b))
ZeroDivisionError: division by zero
```

#### Version and installation information

python 3.6
zarr 2.2.0
numcodecs 0.5.5
Ubuntu

**Comment by alimanfoo** [comment]
Thanks Thomas. I'm not sure if there's anything better we could do here.
Using None as a chunk length for a dimension is mean to indicate use the
total dimension size for the chunk length, i.e., no chunking along the
given dimension, IIRC. If dimension length is zero then chunk  length will
also be zero for a dimension  Ending up with zero for the chunk length
along any dimension is never going to be a good thing, it will always mean
infinite chunks. Maybe a better error message to catch cases like this, and
check we never allow chunk dimensiom length of zero under any circumstances?

**Comment by dstansby** [comment]
I think this is still open for needing a better error message - the one printed on the latest verison of zarr-python is below.
```python
% python test.py 
[]
[3]
Traceback (most recent call last):
  File "/Users/dstansby/software/zarr/zarr-python/test.py", line 16, in <module>
    print(z3[:])
          ~~^^^
  File "/Users/dstansby/software/zarr/zarr-python/zarr/core.py", line 798, in __getitem__
    result = self.get_basic_selection(pure_selection, fields=fields)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dstansby/software/zarr/zarr-python/zarr/core.py", line 924, in get_basic_selection
    return self._get_basic_selection_nd(selection=selection, out=out, fields=fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dstansby/software/zarr/zarr-python/zarr/core.py", line 964, in _get_basic_selection_nd
    indexer = BasicIndexer(selection, self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dstansby/software/zarr/zarr-python/zarr/indexing.py", line 339, in __init__
    dim_indexer = SliceDimIndexer(dim_sel, dim_len, dim_chunk_len)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dstansby/software/zarr/zarr-python/zarr/indexing.py", line 181, in __init__
    self.nchunks = ceildiv(self.dim_len, self.dim_chunk_len)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dstansby/software/zarr/zarr-python/zarr/indexing.py", line 167, in ceildiv
    return math.ceil(a / b)
                     ~~^~~
ZeroDivisionError: division by zero
```

**Comment by maxrjones** [comment]
Closing as part of V2-era issue triage. In V3, `chunks=None` is no longer accepted (you get a clear `TypeError` instead of a silent zero-chunk-length). And zero-length arrays with default chunking work fine:

```python
z = group.create_array('V3', shape=(0,), dtype='i4', fill_value=0)
z[:]  # returns []
```

The original bug (division by zero from chunk length becoming 0) does not reproduce in V3.

Please reopen if this is still relevant.
